backend:
  name: git-gateway

local_backend: true

media_folder: static/assets
public_folder: /assets

display_url: https://dianemahmud.com/

collections:
  - name: blogPost
    label: Blog Post
    folder: src/pages/blog/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template", name: "templateKey", widget: "hidden", default: "blog-post-template"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      #- {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      #- {label: "Featured Image", name: "featuredimage", widget: image}
      #- {label: "Tags", name: "tags", widget: "list"}
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: "Landing Page"
        name: home
        fields:
          - {
              label: "Template",
              name: "templateKey",
              widget: "hidden",
              default: "home-template",
            }
          - {
              label: "Portrait Image",
              name: "portraitImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  {
                    label: "Image Description",
                    name: "imageAlt",
                    widget: "string",
                  },
                ],
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subTitle", widget: "string" }
          - {
              label: "Contact Me button",
              name: "goToContactButtonText",
              widget: "string",
              hint: "This button takes the user to the 'contact me' section.",
            }
          - {
              label: "My Story",
              name: myStory,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Content, name: content, widget: text },
                  { label: Quote, name: quote, widget: text },
                ],
            }
          - {
              label: "My Mission",
              name: myMission,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Content, name: content, widget: text },
                ],
            }
          - {
              label: "Contact Me",
              name: contactMe,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  {
                    label: "Email",
                    name: email,
                    widget: object,
                    fields:
                      [
                        {
                          label: "Show email",
                          name: showEmail,
                          widget: boolean,
                          default: true,
                          hint: "If this is true then the email will not be shown.",
                        },
                        {
                          label: Email,
                          name: email,
                          widget: string,
                          hint: "An email address you do not mind sharing publicly.",
                        },
                      ],
                  },
                  {
                    label: "Message Placeholder",
                    name: messagePlaceHolder,
                    widget: string,
                    hint: "The text that shows up in the message box before someone starts typing.",
                  },
                  {
                    label: "Show first & last name fields",
                    name: showNameFields,
                    widget: boolean,
                    default: true,
                    hint: "If this is true then the first and last name fields are shown.",
                  },
                ],
            }
      - file: src/pages/blog/index.md
        label: "Blog Page"
        name: blog
        fields:
          - {
              label: "Template",
              name: "templateKey",
              widget: "hidden",
              default: "blog-template",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "content", widget: "text" }